=== Mihailorama/gepsio/UnitTests/inlineXBRL-conformanceSuite-2010-04-20/resources/schemas/test.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright 2007 XBRL International. All Rights Reserved. -->
<xs:schema xmlns:conf="http://xbrl.org/2008/conformance" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xbrl.org/2008/conformance" elementFormDefault="qualified" attributeFormDefault="unqualified">
        <xs:element name="testcase">
                <xs:complexType>
                        <xs:sequence>
                                <xs:element ref="conf:creator"/>
                                <xs:element name="number" type="xs:string"/>
                                <xs:element name="name" type="xs:string"/>
                                <xs:element ref="conf:description"/>
                                <xs:element ref="conf:reference" minOccurs="0" maxOccurs="unbounded"/>
                                <xs:element ref="conf:variation" maxOccurs="unbounded"/>
                        </xs:sequence>
                </xs:complexType>
        </xs:element>
        <xs:element name="creator">
                <xs:complexType>
                        <xs:sequence>
                                <xs:element name="name" type="xs:string"/>
                                <xs:element name="email" type="xs:string"/>
                        </xs:sequence>
                </xs:complexType>
        </xs:element>
        <xs:element name="description" type="xs:string"/>
        <xs:element name="reference">
                <xs:complexType>
                        <xs:attribute name="specification" type="xs:string"/>
                        <xs:attribute name="id" type="xs:string"/>
                </xs:complexType>
        </xs:element>
        <xs:element name="variation">
                <xs:complexType>
                        <xs:sequence>
                                <xs:element ref="conf:creator" minOccurs="0"/>
                                <xs:element name="number" type="xs:string" minOccurs="0"/>
                                <xs:element name="name" type="xs:string" minOccurs="0"/>
                                <xs:element ref="conf:description"/>
                                <xs:element ref="conf:reference" minOccurs="0" maxOccurs="unbounded"/>
                                <xs:element ref="conf:data"/>
                                <xs:element ref="conf:result"/>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:ID" use="optional"/>
                </xs:complexType>
        </xs:element>
        <xs:element name="data">
                <xs:complexType>
                        <xs:choice maxOccurs="unbounded">
                                <xs:element ref="conf:schema"/>
                                <xs:element ref="conf:linkbase"/>
                                <xs:element ref="conf:instance"/>
                                <xs:element ref="conf:parameter"/>
                        </xs:choice>
                </xs:complexType>
        </xs:element>
        <xs:element name="schema" type="conf:inputFileType"/>
        <xs:element name="linkbase" type="conf:inputFileType"/>
        <xs:element name="instance" type="conf:inputFileType"/>
        <xs:complexType name="inputFileType">
                <xs:simpleContent>
                        <xs:extension base="xs:string">
                                <xs:attribute name="readMeFirst" type="xs:boolean" use="optional" default="false"/>
                        </xs:extension>
                </xs:simpleContent>
        </xs:complexType>
        <!-- This content model will definitely need some work -->
        <xs:element name="parameter">
                <xs:complexType>
                        <xs:attribute name="name" type="xs:QName"/>
                        <xs:attribute name="datatype" type="xs:QName"/>
                        <xs:attribute name="value" type="xs:string"/>
                </xs:complexType>
        </xs:element>
        <xs:element name="result">
          <xs:complexType>        
              <xs:choice maxOccurs="unbounded">
                  <xs:element name="assertionTests">
                    <xs:complexType>
                      <xs:attribute name="assertionID" type="xs:string"/>
                      <xs:attribute name="countSatisfied" type="xs:integer"/>
                      <xs:attribute name="countNotSatisfied" type="xs:integer"/>
                    </xs:complexType>
                  </xs:element>
                  <xs:element name="instance" type="xs:anyURI" />
                  <xs:element name="error" type="xs:QName" />
              </xs:choice>
      <xs:attribute name="expected" use="optional">
        <xs:simpleType>
          <xs:restriction base="xs:token">
            <xs:enumeration value="valid"/>
            <xs:enumeration value="invalid"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
                </xs:complexType>
        </xs:element>
</xs:schema>

=== Mihailorama/gepsio/JeffFerguson.Test.Gepsio/XBRL-CONF-CR5-2012-01-24/Common/related-standards/xlink/arc-duplication/arc-duplication-testcase.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v5 rel. 4 U (http://www.xmlspy.com) by Walter Hamscher (Standard Advantage) -->
<!-- XBRL 2.1 Tests -->
<!-- Copyright 2003 XBRL International. All Rights Reserved. -->
<?xml-stylesheet type="text/xsl" href="../../../../testcase.xsl"?>
<testcase xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="XLink Label" description="XLink Arc Duplication tests.  From XLink 1.0: Constraint: No Arc Duplication

Each arc-type element must have a pair of from and to values that does not repeat the from and to values (respectively) for any other arc-type element in the same extended link; that is, each pair in a link must be unique.

" outpath="out" owner="fischer@markv.com" xsi:noNamespaceSchemaLocation="../../..//lib/test.xsd" minimal="true">
        <variation id="V-04" name="XLink Arc Duplication tests">
                <description>202.04  Arc-type elements connecting the same "from" and "to" labels MUST appear in different extended-type link elements even if the arcrole attributes are equal.  This is an XLink constraint.</description>
                <data>
                        <xsd readMeFirst="false">202-04-XLinkLabelCounterExample.xsd</xsd>
                        <linkbase readMeFirst="true">202-04-XLinkLabelCounterExample-definition.xml</linkbase>
                </data>
                <result expected="invalid"/>
        </variation>
        <variation id="V-04a" name="XLink Label Counterexample, Presentation LB with attributes">
                <description>202.04a.  Similar to 202.04 above, but presentation linkbase uses same arcRole on both arcs and each has the usual XBRL order, use, and priority, to appear like a proper ordinary arc override.</description>
                <data>
                        <xsd readMeFirst="false">202-04a-XLinkLabelCounterExample.xsd</xsd>
                        <linkbase readMeFirst="true">202-04a-XLinkLabelCounterExample-presentation.xml</linkbase>
                </data>
                <result expected="invalid"/>
        </variation>
        <variation id="V-04b" name="XLink Label Counterexample, Label LB with attributes">
                <description>202.04b.  Similar to 202.04 above, but label linkbase uses same arcRole on both arcs and each has the usual XBRL order, use, and priority, to appear like a proper ordinary arc override.</description>
                <data>
                        <xsd readMeFirst="false">202-04b-XLinkLabelCounterExample.xsd</xsd>
                        <linkbase readMeFirst="true">202-04b-XLinkLabelCounterExample-label.xml</linkbase>
                </data>
                <result expected="invalid"/>
        </variation>
        <variation id="V-04c" name="XLink Label Counterexample, custom arc duplicated">
                <description>202.04c.  Similar to 202.04 above, but custom arc uses same arcRole on both arcs and each has the usual XBRL order, use, and priority, to appear like a proper ordinary arc override.  Also, like 220 series tests, the linkbase is in the xsd to be sure that appinfo-contained linkbases are XLink validated.</description>
                <data>
                        <xsd readMeFirst="true">202-04c-XLinkLabelCounterExample.xsd</xsd>
                </data>
                <result expected="invalid"/>
        </variation>
</testcase>

=== Mihailorama/gepsio/JeffFerguson.Test.Gepsio/XBRL-CONF-CR5-2012-01-24/Common/300-instance/314-lax-validation-testcase.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- XBRL 2.1 Tests -->
<!-- Copyright 2008 XBRL International Inc.  See www.xbrl.org/legal.  All Rights Reserved. -->
<?xml-stylesheet type="text/xsl" href="../../testcase.xsl"?>
<testcase xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
name="LAX validation tests" 
xsi:noNamespaceSchemaLocation="../lib/test.xsd"
outpath="out"
description="Test that LAX validation is performed" 
owner="fischer@markv.com" 
minimal="true">

        <variation id="V-01" name="v01-undefined element and attributes are permitted">
                <description>
                    Segment has an element for which there is no definition, so it is allowed; item has an attribute with no definition, so it is allowed.  The definitions are imported to the discovered taxonomy.
                </description>
                <data>
                        <xsd readMeFirst="false">314-lax-validation-01.xsd</xsd>
                        <instance readMeFirst="true">314-lax-validation-01.xml</instance>
                </data>
                <result expected="valid"/>
        </variation>

        <variation id="V-02" name="v02-undefined element and attributes are permitted">
                <description>
                    Segment has an element for which there is no definition, so it is allowed; item has an attribute with no definition, so it is allowed.  The definitions are found by schemaLocation from the instance document.
                </description>
                <data>
                        <xsd readMeFirst="false">314-lax-validation-02.xsd</xsd>
                        <instance readMeFirst="true">314-lax-validation-02.xml</instance>
                </data>
                <result expected="valid"/>
        </variation>

        <variation id="V-03" name="v03-segment-string-in-integer-element">
                <description>
                    Same as v-01 but segment has an element defined as integer with string contents
                </description>
                <data>
                        <xsd readMeFirst="false">314-lax-validation-01.xsd</xsd>
                        <instance readMeFirst="true">314-lax-validation-03.xml</instance>
                </data>
                <result expected="invalid"/>
        </variation>

        <variation id="V-04" name="v04-item-string-in-integer-attribute">
                <description>
                    Same as v-01 but item has an attribute defined as integer with string contents
                </description>
                <data>
                        <xsd readMeFirst="false">314-lax-validation-01.xsd</xsd>
                        <instance readMeFirst="true">314-lax-validation-04.xml</instance>
                </data>
                <result expected="invalid"/>
        </variation>

        <variation id="V-05" name="v05-segment-string-in-integer-element">
                <description>
                    Same as v-02 but segment has an element defined as integer with string contents
                </description>
                <data>
                        <xsd readMeFirst="false">314-lax-validation-01.xsd</xsd>
                        <instance readMeFirst="true">314-lax-validation-05.xml</instance>
                </data>
                <result expected="invalid"/>
        </variation>

        <variation id="V-06" name="v06-item-string-in-integer-attribute">
                <description>
                    Same as v-02 but item has an attribute defined as integer with string contents
                </description>
                <data>
                        <xsd readMeFirst="false">314-lax-validation-01.xsd</xsd>
                        <instance readMeFirst="true">314-lax-validation-06.xml</instance>
                </data>
                <result expected="invalid"/>
        </variation>


</testcase>

=== Mihailorama/gepsio/UnitTests/XBRL-CONF-CR5-2012-01-24/Common/100-schema/160-UsedOn.xml
<!-- XBRL 2.1 Tests -->
<!-- Copyright 2003 XBRL International.   See www.xbrl.org/legal.  All Rights Reserved. -->
<?xml-stylesheet type="text/xsl" href="../../testcase.xsl"?>

<testcase name="UsedOn" description="Section 5.1.3.4 and Section 5.1.4.5 - The element where the role/arcrole is used MUST correspont to an instance of the QName defined in the roleType/arcroleType declaration but ONLY if it is used inside a standard extended link or in a custom extended link with a roleRef/arcroleRef pointing to the roleType/arcroleType declaration" outpath="out" owner="spec@xbrl.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../lib/test.xsd">

	<variation id="V-01" name="160-01-roleType-standard-linkbase-incorrect-element-Invalid">
		<description>A new roleType definition contains a usedOn element pointing to a valid QName but a standard linkbase uses it in a different element (a label resource)- Invalid</description>
		<data>
			<xsd readMeFirst="true">160-01-roleType-standard-linkbase-incorrect-element-Invalid.xsd</xsd>
		</data>
		<result expected="invalid"/>
	</variation>
	
	<variation id="V-02" name="160-02-roleType-standard-linkbase-incorrect-element-Invalid">
		<description>A new roleType definition contains a usedOn element pointing to a valid QName but a standard linkbase uses it in a different element (a labelLink element)- Invalid</description>
		<data>
			<xsd readMeFirst="true">160-02-roleType-standard-linkbase-incorrect-element-Invalid.xsd</xsd>
		</data>
		<result expected="invalid"/>
	</variation>

	<variation id="V-04" name="160-04-roleType-non-standard-linkbase-incorrect-element-Valid">
		<description>A new roleType definition contains a usedOn element pointing to a valid QName; a custom linkbase uses it in a different element but there is no a roleRef pointing to the roleType declaration - Valid</description>
		<data>
			<xsd readMeFirst="true">160-04-roleType-non-standard-linkbase-incorrect-element-Valid.xsd</xsd>
		</data>
		<result expected="valid"/>
	</variation>

	<variation id="V-05" name="160-05-roleType-non-standard-linkbase-incorrect-element-invalid">
		<description>This is the same 160-04 test case but the hidden schema imports a new taxonomy in the DTS. That imported schema is not a valid taxonomy and it should be ignored because it is not in the DTS. - valid</description>
		<data>
			<xsd readMeFirst="true">160-05-roleType-non-standard-linkbase-incorrect-element-invalid.xsd</xsd>
		</data>
		<result expected="valid"/>
	</variation>
	
	<variation id="V-06" name="160-06-roleType-UsedOnArcElement-valid">
		<description>A role that is only used on elements that cannot accept an xlink:role attribute is nonsensical but valid.</description>
		<data>
			<xsd readMeFirst="true">RoleUsedOnArcElement.xsd</xsd>
		</data>
		<result expected="valid"/>
	</variation>
	
	<variation id="V-07" name="160-07-arcroleType-UsedOnNonArcElements-valid">
		<description>An arcrole that is only used on elements that cannot accept an xlink:arcrole attribute is nonsensical but valid.</description>
		<data>
			<xsd readMeFirst="true">ArcroleUsedOnNonArcElements.xsd</xsd>
		</data>
		<result expected="valid"/>
	</variation>
	
		<variation id="V-08" name="160-08-UsedOnSEquality-valid">
		<description>The UsedOn values are not S-Equal even though they have the same namespace prefix and element name, because the namespace prefixes resolve to different namespaces.</description>
		<data>
			<xsd readMeFirst="true">UsedOnSEquality-valid.xsd</xsd>
		</data>
		<result expected="valid"/>
	</variation>
	
		<variation id="V-09" name="160-09-arcroleType-UsedOnNonArcElements-valid">
		<description>The UsedOn values are S-Equal even though they have different namespace prefixes, because the namespace prefixes resolve to the same namespace.</description>
		<data>
			<xsd readMeFirst="true">UsedOnSEquality-invalid.xsd</xsd>
		</data>
		<result expected="invalid"/>
	</variation>

</testcase>

=== Mihailorama/gepsio/UnitTests/XBRL-CONF-CR3-2007-03-05/Common/schema/160-UsedOn.xml
<!-- XBRL 2.1 Tests -->
<!-- Copyright 2003 XBRL International.   See www.xbrl.org/legal.  All Rights Reserved. -->
<?xml-stylesheet type="text/xsl" href="../../testcase.xsl"?>

<testcase name="UsedOn" description="Section 5.1.3.4 and Section 5.1.4.5 - The element where the role/arcrole is used MUST correspont to an instance of the QName defined in the roleType/arcroleType declaration but ONLY if it is used inside a standard extended link or in a custom extended link with a roleRef/arcroleRef pointing to the roleType/arcroleType declaration" outpath="out" owner="ihr@xbrl.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../lib/test.xsd">

	<variation name="160-01-roleType-standard-linkbase-incorrect-element-Invalid">
		<description>A new roleType definition contains a usedOn element pointing to a valid QName but a standard linkbase uses it in a different element (a label resource)- Invalid</description>
		<data>
			<xsd readMeFirst="true">160-01-roleType-standard-linkbase-incorrect-element-Invalid.xsd</xsd>
		</data>
		<result expected="invalid"/>
	</variation>
	
	<variation name="160-02-roleType-standard-linkbase-incorrect-element-Invalid">
		<description>A new roleType definition contains a usedOn element pointing to a valid QName but a standard linkbase uses it in a different element (a labelLink element)- Invalid</description>
		<data>
			<xsd readMeFirst="true">160-02-roleType-standard-linkbase-incorrect-element-Invalid.xsd</xsd>
		</data>
		<result expected="invalid"/>
	</variation>

	<variation name="160-03-roleType-non-standard-linkbase-incorrect-element-Invalid">
		<description>The roleURI http://www.xbrl.org/2007/role/custom-but-hidden is declared to be used on link:linkbaseRef elements on the usedOn element of the roleType declaration. It is used on a c:customLink element and there is a roleRef declaration pointing to the roleType. So it is invalid. - Invalid</description>
		<data>
			<xsd readMeFirst="true">160-03-roleType-non-standard-linkbase-incorrect-element-Invalid.xsd</xsd>
		</data>
		<result expected="invalid"/>
	</variation>

	<variation name="160-04-roleType-non-standard-linkbase-incorrect-element-Valid">
		<description>A new roleType definition contains a usedOn element pointing to a valid QName a custom linkbase uses it in a different element but there is no a roleRef pointing to the roleType declaration - Valid</description>
		<data>
			<xsd readMeFirst="true">160-04-roleType-non-standard-linkbase-incorrect-element-Valid.xsd</xsd>
		</data>
		<result expected="valid"/>
	</variation>

	<variation name="160-05-roleType-non-standard-linkbase-incorrect-element-invalid">
		<description>This is the same 160-04 test case but the hidden schema imports a new taxonomy in the DTS. That imported schema is not a valid taxonomy and it should be ignored because it is not in the DTS. - valid</description>
		<data>
			<xsd readMeFirst="true">160-05-roleType-non-standard-linkbase-incorrect-element-invalid.xsd</xsd>
		</data>
		<result expected="valid"/>
	</variation>

</testcase>

=== Mihailorama/gepsio/UnitTests/XBRL-CONF-CR5-2012-01-24/Common/300-instance/395-inferNumericConsistency.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- XBRL 2.1 Tests -->
<!-- Copyright 2003, 2011 XBRL International. All Rights Reserved. -->
<?xml-stylesheet type="text/xsl" href="../../testcase.xsl"?>
<testcase xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="Infer Calculated Value Consistency"
  description="Section 5.2.5.2 The CalculationArc Element" outpath="out" minimal="false" owner="walter@hamscher.com"
  xsi:noNamespaceSchemaLocation="../lib/test.xsd">
  <!-- 
Ensure that the numeric values given in an instance do not contradict the derived values in a PTVI instance;
	-->
  <variation id="V-1" name="InferCalculatedValueConsistencyValid">
    <description>395.01 Valid example of summation-item attribute.</description>
    <data>
      <xsd readMeFirst="false">SummationItem.xsd</xsd>
      <linkbase readMeFirst="false">SummationItem_calculation.xml</linkbase>
      <instance readMeFirst="true">395-01-InferCalculatedValueConsistencyValid.xml</instance>
    </data>
    <result expected="valid">395-01-InferCalculatedValueConsistencyValidOut.xml</result>
  </variation>
  <variation id="V-2" name="InferCalculatedValueConsistencyValidButDiffernetValue">
    <description>395.02 This is a test for detecting inconsistency between value in an Instance and value calculated by
      calculation link. This is set to invalid but the document validity itself is still valid.</description>
    <data>
      <xsd readMeFirst="false">SummationItem.xsd</xsd>
      <linkbase readMeFirst="false">SummationItem_calculation.xml</linkbase>
      <instance readMeFirst="true">395-02-InferCalculatedValueConsistencyDifferentValue.xml</instance>
    </data>
    <result expected="invalid">395-02-InferCalculatedValueConsistencyDifferentValueOut.xml</result>
  </variation>
  <variation id="V-3" name="InferCalculatedValueConsistencyWithDefaultContributorValid">
    <description>395.03 Valid example of summation-item in which a contributor is given a default value and appears in
      the instance with an empty value. The example is valid and there are no calculation inconsistencies.</description>
    <data>
      <xsd readMeFirst="false">SummationItemDefaultContributor.xsd</xsd>
      <instance readMeFirst="true">395-03-InferCalculatedValueConsistencyWithDefaultContributorValid.xml</instance>
    </data>
    <result expected="valid">395-03-InferCalculatedValueConsistencyWithDefaultContributorValidOut.xml</result>
  </variation>
  <variation id="V-4" name="InferCalculatedValueConsistencyWithDefaultContributorMissingInvalid">
    <description>395.04 Invalid example of summation-item in which a contributor is given a default value but does not
      appear in the instance. The output is flagged as invalid although it is merely inconsistent.</description>
    <data>
      <xsd readMeFirst="false">SummationItemDefaultContributor.xsd</xsd>
      <instance readMeFirst="true"
        >395-04-InferCalculatedValueConsistencyWithDefaultContributorMissingInvalid.xml</instance>
    </data>
    <result expected="invalid"
      >395-04-InferCalculatedValueConsistencyWithDefaultContributorMissingInvalidOut.xml</result>
  </variation>
  <variation id="V-5" name="InferCalculatedValueConsistencyWithDefaultScenarioValid">
    <description>395.05 Valid example of summation-item in which a scenario element is given a default value so that two
      otherwise syntactically different contexts are s-equal. </description>
    <data>
      <xsd readMeFirst="false">SummationItemDefaultScenario.xsd</xsd>
      <instance readMeFirst="true">395-05-InferCalculatedValueConsistencyWithDefaultScenarioValid.xml</instance>
    </data>
    <result expected="valid">395-05-InferCalculatedValueConsistencyWithDefaultScenarioValidOut.xml</result>
  </variation>
  <variation id="V-6" name="InferCalculatedValueConsistencyWithDefaultScenarioMissingInvalid">
    <description>395.06 Invalid example of summation-item in which a scenario element is given a default value but
      without the scenario element present it is not enough to make the two contexts s-equal. The output is flagged as
      invalid although it is merely inconsistent.</description>
    <data>
      <xsd readMeFirst="false">SummationItemDefaultScenario.xsd</xsd>
      <instance readMeFirst="true"
        >395-06-InferCalculatedValueConsistencyWithDefaultScenarioMissingInvalid.xml</instance>
    </data>
    <result expected="invalid">395-06-InferCalculatedValueConsistencyWithDefaultScenarioMissingInvalidOut.xml</result>
  </variation>
  <variation id="V-7" name="InferCalculatedValueConsistencyWithScenarioAttributeDefaultValid">
    <description>395.07 Valid example of summation-item in which a scenario element is given a default attribute value so that two
      otherwise syntactically different contexts are s-equal.</description>
    <data>
      <xsd readMeFirst="false">SummationItemDefaultScenario.xsd</xsd>
      <instance readMeFirst="true">395-07-InferCalculatedValueConsistencyWithScenarioAttributeDefaultValid.xml</instance>
    </data>
    <result expected="valid">395-07-InferCalculatedValueConsistencyWithScenarioAttributeDefaultValidOut.xml</result>
  </variation>
  <variation id="V-8" name="InferCalculatedValueConsistencyWithScenarioAttributeMissingInvalid">
    <description>395.08 Invalid example of summation-item in which a scenario element has an attribute with a default value but
      without the scenario attribute present it is not enough to make the two contexts s-equal. The output is flagged as
      invalid although it is merely inconsistent.</description>
    <data>
      <xsd readMeFirst="false">SummationItemDefaultScenario.xsd</xsd>
      <instance readMeFirst="true"
        >395-08-InferCalculatedValueConsistencyWithScenarioAttributeMissingInvalid.xml</instance>
    </data>
    <result expected="invalid">395-08-InferCalculatedValueConsistencyWithScenarioAttributeMissingInvalidOut.xml</result>
  </variation>
</testcase>
