=== Mihailorama/gepsio/UnitTests/inlineXBRL-conformanceSuite-2010-04-20/resources/schemas/test.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright 2007 XBRL International. All Rights Reserved. -->
<xs:schema xmlns:conf="http://xbrl.org/2008/conformance" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xbrl.org/2008/conformance" elementFormDefault="qualified" attributeFormDefault="unqualified">
        <xs:element name="testcase">
                <xs:complexType>
                        <xs:sequence>
                                <xs:element ref="conf:creator"/>
                                <xs:element name="number" type="xs:string"/>
                                <xs:element name="name" type="xs:string"/>
                                <xs:element ref="conf:description"/>
                                <xs:element ref="conf:reference" minOccurs="0" maxOccurs="unbounded"/>
                                <xs:element ref="conf:variation" maxOccurs="unbounded"/>
                        </xs:sequence>
                </xs:complexType>
        </xs:element>
        <xs:element name="creator">
                <xs:complexType>
                        <xs:sequence>
                                <xs:element name="name" type="xs:string"/>
                                <xs:element name="email" type="xs:string"/>
                        </xs:sequence>
                </xs:complexType>
        </xs:element>
        <xs:element name="description" type="xs:string"/>
        <xs:element name="reference">
                <xs:complexType>
                        <xs:attribute name="specification" type="xs:string"/>
                        <xs:attribute name="id" type="xs:string"/>
                </xs:complexType>
        </xs:element>
        <xs:element name="variation">
                <xs:complexType>
                        <xs:sequence>
                                <xs:element ref="conf:creator" minOccurs="0"/>
                                <xs:element name="number" type="xs:string" minOccurs="0"/>
                                <xs:element name="name" type="xs:string" minOccurs="0"/>
                                <xs:element ref="conf:description"/>
                                <xs:element ref="conf:reference" minOccurs="0" maxOccurs="unbounded"/>
                                <xs:element ref="conf:data"/>
                                <xs:element ref="conf:result"/>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:ID" use="optional"/>
                </xs:complexType>
        </xs:element>
        <xs:element name="data">
                <xs:complexType>
                        <xs:choice maxOccurs="unbounded">
                                <xs:element ref="conf:schema"/>
                                <xs:element ref="conf:linkbase"/>
                                <xs:element ref="conf:instance"/>
                                <xs:element ref="conf:parameter"/>
                        </xs:choice>
                </xs:complexType>
        </xs:element>
        <xs:element name="schema" type="conf:inputFileType"/>
        <xs:element name="linkbase" type="conf:inputFileType"/>
        <xs:element name="instance" type="conf:inputFileType"/>
        <xs:complexType name="inputFileType">
                <xs:simpleContent>
                        <xs:extension base="xs:string">
                                <xs:attribute name="readMeFirst" type="xs:boolean" use="optional" default="false"/>
                        </xs:extension>
                </xs:simpleContent>
        </xs:complexType>
        <!-- This content model will definitely need some work -->
        <xs:element name="parameter">
                <xs:complexType>
                        <xs:attribute name="name" type="xs:QName"/>
                        <xs:attribute name="datatype" type="xs:QName"/>
                        <xs:attribute name="value" type="xs:string"/>
                </xs:complexType>
        </xs:element>
        <xs:element name="result">
          <xs:complexType>        
              <xs:choice maxOccurs="unbounded">
                  <xs:element name="assertionTests">
                    <xs:complexType>
                      <xs:attribute name="assertionID" type="xs:string"/>
                      <xs:attribute name="countSatisfied" type="xs:integer"/>
                      <xs:attribute name="countNotSatisfied" type="xs:integer"/>
                    </xs:complexType>
                  </xs:element>
                  <xs:element name="instance" type="xs:anyURI" />
                  <xs:element name="error" type="xs:QName" />
              </xs:choice>
      <xs:attribute name="expected" use="optional">
        <xs:simpleType>
          <xs:restriction base="xs:token">
            <xs:enumeration value="valid"/>
            <xs:enumeration value="invalid"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
                </xs:complexType>
        </xs:element>
</xs:schema>

=== Mihailorama/gepsio/UnitTests/XBRL-CONF-CR5-2012-01-24/Common/100-schema/161-Appinfo.xml
<!-- XBRL 2.1 Tests -->
<!-- Copyright 2003 XBRL International.   See www.xbrl.org/legal.  All Rights Reserved. -->
<?xml-stylesheet type="text/xsl" href="../../testcase.xsl"?>

<testcase name="Appinfo"
	description="Section 3.4 
	''XBRL instances, XBRL linkbases and XBRL taxonomy schemas MUST comply with the
	syntax requirements imposed in this specification. Many of these syntax
	requirements are expressed using XML Schemas so a part of the validation
	process can be performed using XML Schema validation software.''
	
	Since annotation/appinfo stipulates lax validation, any processor that chooses
	to satisfy section 3.4 by employing a validating XML parser (such as Xerces)
	has a responsibility to ensure that the appropriate declarations for XBRL
	components are provided to that parser."
	outpath="out" owner="spec@xbrl.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../lib/test.xsd">
	<!-- role tests -->
	<variation id="V-01" name="161-01-roleType-id-missing">
		<description>A role type declaration with a missing id. Valid, but useless.</description>
		<data>
			<xsd readMeFirst="true">161-01-roleType-id-missing-valid.xsd</xsd>
		</data>
		<result expected="valid"/>
	</variation>
	<variation id="V-02" name="161-02-roleType-id-notncname">
		<description>A role type declaration with an id not an ncname. Invalid.</description>
		<data>
			<xsd readMeFirst="true">161-02-roleType-id-notncname-invalid.xsd</xsd>
		</data>
		<result expected="invalid"/>
	</variation>
	<variation id="V-03" name="161-03-roleType-uri-missing">
		<description>A role type declaration with a missing roleURI. Invalid.</description>
		<data>
			<xsd readMeFirst="true">161-03-roleType-uri-missing-invalid.xsd</xsd>
		</data>
		<result expected="invalid"/>
	</variation>
	<variation id="V-04" name="161-04-roleType-uri-empty">
		<description>A role type declaration with an empty roleURI. Invalid.</description>
		<data>
			<xsd readMeFirst="true">161-04-roleType-uri-empty-invalid.xsd</xsd>
		</data>
		<result expected="invalid"/>
	</variation>
	<variation id="V-05" name="161-05-roleType-uri-notabsolute">
		<description>A role type declaration with roleURI not absolute. Invalid. Section
			5.1.3 -- This isn't actually invalid according to the 2008-07-02 spec; discussion required</description>
		<data>
			<xsd readMeFirst="true">161-05-roleType-uri-notabsolute-invalid.xsd</xsd>
		</data>
		<result expected="valid"/>
	</variation>
	<!-- Arcrole tests -->
	<variation id="V-11" name="161-11-arcroleType-id-missing">
		<description>A arcrole type declaration with a missing id. Valid, but useless.</description>
		<data>
			<xsd readMeFirst="true">161-11-arcroleType-id-missing-valid.xsd</xsd>
		</data>
		<result expected="valid"/>
	</variation>
	<variation id="V-12" name="161-12-arcroleType-id-notncname">
		<description>A arcrole type declaration with an id not an ncname. Invalid.</description>
		<data>
			<xsd readMeFirst="true">161-12-arcroleType-id-notncname-invalid.xsd</xsd>
		</data>
		<result expected="invalid"/>
	</variation>
	<variation id="V-13" name="161-13-arcroleType-uri-missing">
		<description>A arcrole type declaration with a missing arcroleURI. Invalid.</description>
		<data>
			<xsd readMeFirst="true">161-13-arcroleType-uri-missing-invalid.xsd</xsd>
		</data>
		<result expected="invalid"/>
	</variation>
	<variation id="V-14" name="161-14-arcroleType-uri-empty">
		<description>A arcrole type declaration with an empty arcroleURI. Invalid.</description>
		<data>
			<xsd readMeFirst="true">161-14-arcroleType-uri-empty-invalid.xsd</xsd>
		</data>
		<result expected="invalid"/>
	</variation>
	<variation id="V-15" name="161-15-arcroleType-uri-noturi">
		<description>A arcrole type declaration with arcroleURI not absolute. Invalid. Section
			5.1.3</description>
		<data>
			<xsd readMeFirst="true">161-15-arcroleType-uri-noturi-invalid.xsd</xsd>
		</data>
		<result expected="invalid"/>
	</variation>
	<variation id="V-16" name="161-16-arcroleType-cyclesAllowedAll">
		<description>A arcrole type declaration with cyclesAllowed = All Invalid. Section
			5.1.3</description>
		<data>
			<xsd readMeFirst="true">161-16-arcroleType-cyclesAllowedAll-invalid.xsd</xsd>
		</data>
		<result expected="invalid"/>
	</variation>
</testcase>
