=== Mihailorama/gepsio/UnitTests/inlineXBRL-conformanceSuite-2010-04-20/resources/schemas/test.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright 2007 XBRL International. All Rights Reserved. -->
<xs:schema xmlns:conf="http://xbrl.org/2008/conformance" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xbrl.org/2008/conformance" elementFormDefault="qualified" attributeFormDefault="unqualified">
        <xs:element name="testcase">
                <xs:complexType>
                        <xs:sequence>
                                <xs:element ref="conf:creator"/>
                                <xs:element name="number" type="xs:string"/>
                                <xs:element name="name" type="xs:string"/>
                                <xs:element ref="conf:description"/>
                                <xs:element ref="conf:reference" minOccurs="0" maxOccurs="unbounded"/>
                                <xs:element ref="conf:variation" maxOccurs="unbounded"/>
                        </xs:sequence>
                </xs:complexType>
        </xs:element>
        <xs:element name="creator">
                <xs:complexType>
                        <xs:sequence>
                                <xs:element name="name" type="xs:string"/>
                                <xs:element name="email" type="xs:string"/>
                        </xs:sequence>
                </xs:complexType>
        </xs:element>
        <xs:element name="description" type="xs:string"/>
        <xs:element name="reference">
                <xs:complexType>
                        <xs:attribute name="specification" type="xs:string"/>
                        <xs:attribute name="id" type="xs:string"/>
                </xs:complexType>
        </xs:element>
        <xs:element name="variation">
                <xs:complexType>
                        <xs:sequence>
                                <xs:element ref="conf:creator" minOccurs="0"/>
                                <xs:element name="number" type="xs:string" minOccurs="0"/>
                                <xs:element name="name" type="xs:string" minOccurs="0"/>
                                <xs:element ref="conf:description"/>
                                <xs:element ref="conf:reference" minOccurs="0" maxOccurs="unbounded"/>
                                <xs:element ref="conf:data"/>
                                <xs:element ref="conf:result"/>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:ID" use="optional"/>
                </xs:complexType>
        </xs:element>
        <xs:element name="data">
                <xs:complexType>
                        <xs:choice maxOccurs="unbounded">
                                <xs:element ref="conf:schema"/>
                                <xs:element ref="conf:linkbase"/>
                                <xs:element ref="conf:instance"/>
                                <xs:element ref="conf:parameter"/>
                        </xs:choice>
                </xs:complexType>
        </xs:element>
        <xs:element name="schema" type="conf:inputFileType"/>
        <xs:element name="linkbase" type="conf:inputFileType"/>
        <xs:element name="instance" type="conf:inputFileType"/>
        <xs:complexType name="inputFileType">
                <xs:simpleContent>
                        <xs:extension base="xs:string">
                                <xs:attribute name="readMeFirst" type="xs:boolean" use="optional" default="false"/>
                        </xs:extension>
                </xs:simpleContent>
        </xs:complexType>
        <!-- This content model will definitely need some work -->
        <xs:element name="parameter">
                <xs:complexType>
                        <xs:attribute name="name" type="xs:QName"/>
                        <xs:attribute name="datatype" type="xs:QName"/>
                        <xs:attribute name="value" type="xs:string"/>
                </xs:complexType>
        </xs:element>
        <xs:element name="result">
          <xs:complexType>        
              <xs:choice maxOccurs="unbounded">
                  <xs:element name="assertionTests">
                    <xs:complexType>
                      <xs:attribute name="assertionID" type="xs:string"/>
                      <xs:attribute name="countSatisfied" type="xs:integer"/>
                      <xs:attribute name="countNotSatisfied" type="xs:integer"/>
                    </xs:complexType>
                  </xs:element>
                  <xs:element name="instance" type="xs:anyURI" />
                  <xs:element name="error" type="xs:QName" />
              </xs:choice>
      <xs:attribute name="expected" use="optional">
        <xs:simpleType>
          <xs:restriction base="xs:token">
            <xs:enumeration value="valid"/>
            <xs:enumeration value="invalid"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
                </xs:complexType>
        </xs:element>
</xs:schema>

=== Mihailorama/gepsio/JeffFerguson.Test.Gepsio/XBRL-CONF-CR5-2012-01-24/Common/200-linkbase/214-lax-validation-testcase.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- XBRL 2.1 Tests -->
<!-- Copyright 2008 XBRL International Inc.  See www.xbrl.org/legal.  All Rights Reserved. -->
<?xml-stylesheet type="text/xsl" href="../../testcase.xsl"?>
<testcase xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
name="LAX validation tests" 
xsi:noNamespaceSchemaLocation="../lib/test.xsd"
outpath="out"
description="Test that LAX validation is performed" 
owner="fischer@markv.com" 
minimal="true">

        <variation id="V-01" name="v01-label-undefined-attribute">
                <description>
                    Label has an attribute which is undefined.  Linkbase schema allows anyAttribute of xml namespace with lax processing.
                </description>
                <data>
                        <xsd readMeFirst="true">214-lax-validation-01.xsd</xsd>
                        <linkbase readMeFirst="false">214-lax-validation-01-label.xml</linkbase>
                </data>
                <result expected="valid"/>
        </variation>

        <variation id="V-02" name="v02-label-invalid-xmlspace-attribute">
                <description>
                    same as V-01 but has an invalid value in xml:space attribute (lax)
                </description>
                <data>
                        <xsd readMeFirst="true">214-lax-validation-02.xsd</xsd>
                        <linkbase readMeFirst="false">214-lax-validation-02-label.xml</linkbase>
                </data>
                <result expected="invalid"/>
        </variation>

        <variation id="V-03" name="v03-label-valid-xml-lang-attribute">
                <description>
                    same as V-01 but has an valid value in xml:lang attribute (lax).
                    (note that the original xs:language pattern would have failed this code, but
                     the errata in http://www.w3.org/2001/05/xmlschema-errata#E2-25 makes this value legal)
                </description>
                <data>
                        <xsd readMeFirst="true">214-lax-validation-03.xsd</xsd>
                        <linkbase readMeFirst="false">214-lax-validation-03-label.xml</linkbase>
                </data>
                <result expected="valid"/>
        </variation>
        <variation id="V-04" name="v04-label-invalid-xml-lang-attribute">
                <description>
                    same as V-01 but has an invalid value in xml:lang attribute (lax)
                </description>
                <data>
                        <xsd readMeFirst="true">214-lax-validation-04.xsd</xsd>
                        <linkbase readMeFirst="false">214-lax-validation-04-label.xml</linkbase>
                </data>
                <result expected="invalid"/>
        </variation>


</testcase>

=== Mihailorama/gepsio/UnitTests/XBRL-CONF-CR5-2012-01-24/Common/300-instance/322-XmlXbrlInteraction.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- XBRL 2.1 Tests -->
<!-- Copyright 2011 XBRL International Inc.  See www.xbrl.org/legal.  All Rights Reserved. -->
<?xml-stylesheet type="text/xsl" href="../../testcase.xsl"?>
<testcase xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="XML-XBRL Interaction" description="Checks interaction between XML infoset and XBRL validation for decimals and precision, which are option in schema, but in this case are entered to infoset by default and fixed for calculation binding rules 5_2_5_2 and 4_6_6" outpath="out" owner="fischer@markv.com" xsi:noNamespaceSchemaLocation="../lib/test.xsd" minimal="true">

        <variation id="V-00" name="v00-DecimalDefaulted-Consistent">
                <description>322.00 - Valid</description>
                <data>
                        <xsd readMeFirst="false">322-XmlXbrlInteraction.xsd</xsd>
                        <instance readMeFirst="true">322-00-BindCalculationDefaultDecimals-instance.xbrl</instance>
                </data>
                <result expected="valid"/>
        </variation>

        <variation id="V-01" name="v01-DecimalDefaulted-Consistent">
                <description>322.01 - Invalid</description>
                <data>
                        <xsd readMeFirst="false">322-XmlXbrlInteraction.xsd</xsd>
                        <instance readMeFirst="true">322-01-BindCalculationDefaultDecimals-instance.xbrl</instance>
                </data>
                <result expected="invalid"/>
        </variation>

        <variation id="V-02" name="v00-PrecisionDefaulted-Consistent">
                <description>322.02 - Valid</description>
                <data>
                        <xsd readMeFirst="false">322-XmlXbrlInteraction.xsd</xsd>
                        <instance readMeFirst="true">322-02-BindCalculationDefaultPrecision-instance.xbrl</instance>
                </data>
                <result expected="valid"/>
        </variation>

        <variation id="V-03" name="v01-PrecisionDefaulted-Consistent">
                <description>322.03 - Invalid</description>
                <data>
                        <xsd readMeFirst="false">322-XmlXbrlInteraction.xsd</xsd>
                        <instance readMeFirst="true">322-03-BindCalculationDefaultPrecision-instance.xbrl</instance>
                </data>
                <result expected="invalid"/>
        </variation>

        <variation id="V-04" name="v00-DecimalFixed-Consistent">
                <description>322.04 - Valid</description>
                <data>
                        <xsd readMeFirst="false">322-XmlXbrlInteraction.xsd</xsd>
                        <instance readMeFirst="true">322-04-BindCalculationFixedDecimals-instance.xbrl</instance>
                </data>
                <result expected="valid"/>
        </variation>

        <variation id="V-05" name="v01-PrecisionDefaulted-Consistent">
                <description>322.05 - Invalid</description>
                <data>
                        <xsd readMeFirst="false">322-XmlXbrlInteraction.xsd</xsd>
                        <instance readMeFirst="true">322-05-BindCalculationFixedPrecision-instance.xbrl</instance>
                </data>
                <result expected="valid"/>
        </variation>

</testcase>

=== Mihailorama/gepsio/JeffFerguson.Test.Gepsio/XBRL-CONF-CR5-2012-01-24/Common/100-schema/114-lax-validation-testcase.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- XBRL 2.1 Tests -->
<!-- Copyright 2008 XBRL International Inc.  See www.xbrl.org/legal.  All Rights Reserved. -->
<?xml-stylesheet type="text/xsl" href="../../testcase.xsl"?>
<testcase xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="../lib/test.xsd"
outpath="out"
name="LAX validation tests" 
description="Test that LAX validation is performed" 
owner="fischer@markv.com" 
minimal="true">

        <variation id="V-01" name="v01-passes-undefined-stuff">
                <description>
                    appinfo has an element for which there is no definition, so it is allowed; element has an attribute with no definition, so it is allowed
                </description>
                <data>
                        <xsd readMeFirst="true">114-lax-validation-01.xsd</xsd>
                </data>
                <result expected="valid"/>
        </variation>

        <variation id="V-02" name="v02-appinfo-string-in-integer-element">
                <description>
                    appinfo has an element defined as integer with string contents
                </description>
                <data>
                        <xsd readMeFirst="true">114-lax-validation-02.xsd</xsd>
                </data>
                <result expected="invalid"/>
        </variation>

        <variation id="V-03" name="v03-element-string-in-integer-attribute">
                <description>
                    element has an attribute defined as integer with string contents
                </description>
                <data>
                        <xsd readMeFirst="true">114-lax-validation-03.xsd</xsd>
                </data>
                <result expected="invalid"/>
        </variation>

        <variation id="V-04" name="v04-appinfo-has-linkbase-no-errors">
                <description>
                    appinfo has an embedded linkbase without bad stuff, to be sure that the embedded clean linkbase is processed without error (next variation adds a schema error to the linkbase in the appinfo)
                </description>
                <data>
                        <xsd readMeFirst="true">114-lax-validation-04.xsd</xsd>
                </data>
                <result expected="valid"/>
        </variation>

        <variation id="V-05" name="v05-appinfo-has-linkbase-with-unwanted-element">
                <description>
                    appinfo has an embedded linkbase with defined valid element in unwanted location in linkbase, to ensure that xml validation is being performed on the embedded linkbase
                </description>
                <data>
                        <xsd readMeFirst="true">114-lax-validation-05.xsd</xsd>
                </data>
                <result expected="invalid"/>
        </variation>


</testcase>

=== Mihailorama/gepsio/JeffFerguson.Test.Gepsio/XBRL-CONF-CR5-2012-01-24/Common/200-linkbase/215-ArcroleAndRoleRefs-testcase.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- XBRL 2.1 Tests --><!-- Copyright 2009 XBRL International Inc.  See www.xbrl.org/legal.  All Rights Reserved. --><?xml-stylesheet type="text/xsl" href="../../testcase.xsl"?><testcase xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          name="Duplicate linkbase roleRef and duplicate arcroleRefs"
          description="3.5.2.4.5 and 3.5.2.5.5 linkbase roleRef and arcroleRef elements."
          outpath="out"
          owner="walter@hamscher.com"
          minimal="true"
          xsi:noNamespaceSchemaLocation="../lib/test.xsd">
   <variation id="V-01" name="215-01 duplicate roleRef elements in calculation linkbase">
      <description>215-01-calculation.xml contains two role references to the same URI, INVALID</description>
      <data>
         <xsd readMeFirst="true">215-01.xsd</xsd>
         <linkbase readMeFirst="false">215-01-calculation.xml</linkbase>
      </data>
      <result expected="invalid"/>
   </variation>
   <variation id="V-02" name="215-02 duplicate roleRef elements in definition linkbase">
      <description>215-02-definition.xml contains two role references to the same URI, INVALID</description>
      <data>
         <xsd readMeFirst="true">215-02.xsd</xsd>
         <linkbase readMeFirst="false">215-02-definition.xml</linkbase>
      </data>
      <result expected="invalid"/>
   </variation>
   <variation id="V-03" name="215-03 duplicate roleRef elements in label linkbase">
      <description>215-03-label.xml contains two role references to the same URI, INVALID</description>
      <data>
         <xsd readMeFirst="true">215-03.xsd</xsd>
         <linkbase readMeFirst="false">215-03-label.xml</linkbase>
      </data>
      <result expected="invalid"/>
   </variation>
   <variation id="V-04" name="215-04 duplicate roleRef elements in presentation linkbase">
      <description>215-04-presentation.xml contains two role references to the same URI, INVALID</description>
      <data>
         <xsd readMeFirst="true">215-04.xsd</xsd>
         <linkbase readMeFirst="false">215-04-presentation.xml</linkbase>
      </data>
      <result expected="invalid"/>
   </variation>
   <variation id="V-05" name="215-05 duplicate roleRef elements in reference linkbase">
      <description>215-05-reference.xml contains two role references to the same URI, INVALID</description>
      <data>
         <xsd readMeFirst="true">215-05.xsd</xsd>
         <linkbase readMeFirst="false">215-05-reference.xml</linkbase>
      </data>
      <result expected="invalid"/>
   </variation>
   <variation id="V-06" name="215-06 duplicate arcroleRef elements in calculation linkbase">
      <description>215-06-calculation.xml contains two arcrole references to the same URI, INVALID</description>
      <data>
         <xsd readMeFirst="true">215-06.xsd</xsd>
         <linkbase readMeFirst="false">215-06-calculation.xml</linkbase>
      </data>
      <result expected="invalid"/>
   </variation>
   <variation id="V-07" name="215-07 duplicate arcroleRef elements in definition linkbase">
      <description>215-07-definition.xml contains two arcrole references to the same URI, INVALID</description>
      <data>
         <xsd readMeFirst="true">215-07.xsd</xsd>
         <linkbase readMeFirst="false">215-07-definition.xml</linkbase>
      </data>
      <result expected="invalid"/>
   </variation>
   <variation id="V-08" name="215-08 duplicate arcroleRef elements in label linkbase">
      <description>215-08-label.xml contains two arcrole references to the same URI, INVALID</description>
      <data>
         <xsd readMeFirst="true">215-08.xsd</xsd>
         <linkbase readMeFirst="false">215-08-label.xml</linkbase>
      </data>
      <result expected="invalid"/>
   </variation>
   <variation id="V-09" name="215-09 duplicate arcroleRef elements in presentation linkbase">
      <description>215-09-presentation.xml contains two arcrole references to the same URI, INVALID</description>
      <data>
         <xsd readMeFirst="true">215-09.xsd</xsd>
         <linkbase readMeFirst="false">215-09-presentation.xml</linkbase>
      </data>
      <result expected="invalid"/>
   </variation>
   <variation id="V-10" name="215-10 duplicate arcroleRef elements in reference linkbase">
      <description>215-10-reference.xml contains two arcrole references to the same URI, INVALID</description>
      <data>
         <xsd readMeFirst="true">215-10.xsd</xsd>
         <linkbase readMeFirst="false">215-10-reference.xml</linkbase>
      </data>
      <result expected="invalid"/>
   </variation>
</testcase>

=== Mihailorama/gepsio/UnitTests/XBRL-CONF-CR5-2012-01-24/Common/related-standards/xml-schema/uniqueParticleAttribution/uniqueParticleAttribution-testcase.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- XBRL 2.1 Tests -->
<!-- Copyright 2009 XBRL International Inc.  See www.xbrl.org/legal.  All Rights Reserved. -->
<?xml-stylesheet type="text/xsl" href="../../../../testcase.xsl"?>
<testcase xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
name="Unique Particle Attribution (UPA) xml schema validation tests" 
xsi:noNamespaceSchemaLocation="../../../lib/test.xsd"
outpath="out"
description="Test that LAX validation is performed.  For more information please see http://bugzilla.xbrl.org/show_bug.cgi?id=359.

Unique Particle Attribution (UPA) schema validation should be handled
consistently between XBRL products but Roland Hommes reports it's not (and it
affects his clients).

This inconsistent xml schema validation affects tuples

   &lt;mytuple&gt;
     &lt;balance contextRef='startInstantPeriod'...&gt;xxx ...
     &lt;change1 contextRef='durationPeriod'...&gt;yyy1 ...
     &lt;change2 contextRef='durationPeriod'...&gt;yyy2 ...
     &lt;balance contextRef='endInstantPeriod'...&gt;zzz ...
   &lt;/mytuple&gt;
" 
owner="fischer@markv.com" 
minimal="true">

        <variation id="V-01" name="v01-UPA-schema-validation-test">
                <description>
                    Beginning balance optional, changes required, ending balance optional.
                </description>
                <data>
                        <xsd readMeFirst="true">uniqueParticleAttribution-01.xsd</xsd>
                </data>
                <result expected="valid"/>
        </variation>

        <variation id="V-02" name="v01-UPA-schema-validation-test">
                <description>
                    Beginning balance required, changes optional, ending balance optional.
                </description>
                <data>
                        <xsd readMeFirst="true">uniqueParticleAttribution-02.xsd</xsd>
                </data>
                <result expected="valid"/>
        </variation>

        <variation id="V-03" name="v03-UPA-schema-validation-test">
                <description>
                    Beginning balance optional, changes optional, ending balance required.
                </description>
                <data>
                        <xsd readMeFirst="true">uniqueParticleAttribution-03.xsd</xsd>
                </data>
                <result expected="invalid"/>
        </variation>

        <variation id="V-04" name="v04-UPA-schema-validation-test">
                <description>
                    Beginning balance required, changes required, ending balance optional.
                </description>
                <data>
                        <xsd readMeFirst="true">uniqueParticleAttribution-04.xsd</xsd>
                </data>
                <result expected="valid"/>
        </variation>

        <variation id="V-05" name="v05-UPA-schema-validation-test">
                <description>
                    Beginning balance required, changes required, ending balance required.
                </description>
                <data>
                        <xsd readMeFirst="true">uniqueParticleAttribution-05.xsd</xsd>
                </data>
                <result expected="valid"/>
        </variation>

        <variation id="V-06" name="v06-UPA-schema-validation-test">
                <description>
                    Beginning balance optional, changes optional, ending balance optional.
                </description>
                <data>
                        <xsd readMeFirst="true">uniqueParticleAttribution-06.xsd</xsd>
                </data>
                <result expected="invalid"/>
        </variation>


</testcase>

=== Mihailorama/gepsio/UnitTests/XBRL-CONF-CR5-2012-01-24/Common/100-schema/115-ArcroleAndRoleRefs-testcase.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- XBRL 2.1 Tests --><!-- Copyright 2009 XBRL International Inc. See www.xbrl.org/legal. All Rights Reserved. --><?xml-stylesheet type="text/xsl" href="../../testcase.xsl"?><testcase xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          name="Duplicate linkbase roleRef and duplicate arcroleRefs"
          description="3.5.2.4.5 and 3.5.2.5.5 linkbase roleRef and arcroleRef elements."
          outpath="out"
          owner="walter@hamscher.com"
          minimal="true"
          xsi:noNamespaceSchemaLocation="../lib/test.xsd">
   <variation id="V-01" name="115-01 duplicate roleRef elements in definition linkbase">
      <description>115-01.xsd contains two role references to the same URI in different linkbases, VALID.</description>
      <data>
         <xsd readMeFirst="true">115-01.xsd</xsd>
      </data>
      <result expected="valid"/>
   </variation>
   <variation id="V-02" name="115-02 duplicate roleRef elements in definition linkbase">
      <description>115-02.xsd contains two role references to the same URI in the same linkbase, INVALID.</description>
      <data>
         <xsd readMeFirst="true">115-02.xsd</xsd>
      </data>
      <result expected="invalid"/>
   </variation>
   <variation id="V-03" name="115-03 duplicate arcroleRef elements in definition linkbase">
      <description>115-03.xsd contains two arcrole references to the same URI in different linkbases, VALID.</description>
      <data>
         <xsd readMeFirst="true">115-03.xsd</xsd>
      </data>
      <result expected="valid"/>
   </variation>
   <variation id="V-04" name="115-04 duplicate arcroleRef elements in definition linkbase">
      <description>115-04.xsd contains two arcrole references to the same URI in the same linkbase, INVALID.</description>
      <data>
         <xsd readMeFirst="true">115-04.xsd</xsd>
      </data>
      <result expected="invalid"/>
   </variation>
</testcase>

=== Mihailorama/gepsio/UnitTests/XBRL-CONF-CR5-2012-01-24/Common/300-instance/308-ArcroleAndRoleRefs-testcase.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- XBRL 2.1 Tests --><!-- Copyright 2009 XBRL International Inc.  See www.xbrl.org/legal.  All Rights Reserved. --><?xml-stylesheet type="text/xsl" href="../../testcase.xsl"?><testcase xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          name="Duplicate instance roleRef and duplicate arcroleRefs"
          description="3.5.2.4.5 and 3.5.2.5.5 duplicate instance roleRef and arcroleRef elements."
          outpath="out"
          owner="walter@hamscher.com"
          minimal="true"
          xsi:noNamespaceSchemaLocation="../lib/test.xsd">
   <variation id="V-01" name="308-01 duplicate roleRef elements in instance">
      <description>Instance contains two role references to the same URI, INVALID</description>
      <data>
         <xsd readMeFirst="false">308-01.xsd</xsd>
         <instance readMeFirst="true">308-01-instance.xml</instance>
      </data>
      <result expected="invalid"/>
   </variation>
   <variation id="V-02" name="308-02 duplicate arcroleRef elements in instance">
      <description>Instance contains two arcrole references to the same URI, INVALID</description>
      <data>
         <xsd readMeFirst="false">308-02.xsd</xsd>
         <instance readMeFirst="true">308-02-instance.xml</instance>
      </data>
      <result expected="invalid"/>
   </variation>
</testcase>

=== Mihailorama/gepsio/UnitTests/XBRL-CONF-CR5-2012-01-24/Common/400-misc/400-nestedElements.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- XBRL 2.1 Tests -->
<!-- See http://bugzilla.xbrl.org/show_bug.cgi?id=369 -->
<!-- Copyright 2003 XBRL International Inc.  See www.xbrl.org/legal.  All Rights Reserved. -->

<?xml-stylesheet type="text/xsl" href="../../testcase.xsl"?>

<testcase xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="Nested XBRL" description="Tests XBRL constructs nested in XML containers" outpath="out" owner="cps@descionsoft.com" xsi:noNamespaceSchemaLocation="../lib/test.xsd" minimal="true">

  <variation id="v01" name="400-01 single nested instance">
  	<description>Single instance nested in an XML container.</description>
  	<data>
  		<xsd readMeFirst="false">400-nestedInstanceTaxonomySchema.xsd</xsd>
  		<instance readMeFirst="true">400-01-singleNestedInstance.xml</instance>
  	</data>
  	<result expected="invalid"/>
  </variation>
  
  <variation id="v02" name="400-02 multiple nested instances">
    <description>Multiple instances nested in an XML container.</description>
    <data>
      <xsd readMeFirst="false">400-nestedInstanceTaxonomySchema.xsd</xsd>
      <instance readMeFirst="true">400-02-multipleNestedInstances.xml</instance>
    </data>
    <result expected="invalid"/>
  </variation>
  
  <variation id="v03" name="400-03 single nested schema">
    <description>Single schema nested in an XML container.</description>
    <data>
      <xsd readMeFirst="true">400-03-singleNestedSchema.xsd</xsd>
    </data>
    <result expected="invalid"/>
  </variation>
  
  <variation id="v04" name="400-04 multiple nested schemas">
    <description>Multiple schemas nested in an XML container.</description>
    <data>
      <xsd readMeFirst="true">400-04-multipleNestedSchemas.xsd</xsd>
    </data>
    <result expected="invalid"/>
  </variation>
  
  <variation id="v05" name="400-05 single nested linkbase">
    <description>Single schema nested in an XML container.</description>
    <data>
      <linkbase readMeFirst="true">400-05-singleNestedLinkbase.xsd</linkbase>
    </data>
    <result expected="invalid"/>
  </variation>
  
  <variation id="v06" name="400-06 multiple nested linkbases">
    <description>Multiple schemas nested in an XML container.</description>
    <data>
      <linkbase readMeFirst="true">400-06-multipleNestedLinkbases.xsd</linkbase>
    </data>
    <result expected="invalid"/>
  </variation>

</testcase>
